networks:
  frontend:
    name: frontend
  backend:
    name: backend
  database:
    name: database

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: whatdayistoday
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: 
      context: ./backend/app
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whatdayistoday
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
    expose:
      - "8080"
    networks:
      - backend
      - database
  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
      args:
        - MAVEN_OPTS=-Dmaven.repo.local=/root/.m2/repository
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - postgres
      - app
    environment:
      APP_SERVICE_URL: http://app:8080
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/whatdayistoday
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    expose:
      - "8081"
    networks:
      - backend
      - database
  web:
    container_name: web
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "8000"
    depends_on:
      - app
      - gateway
    networks:
      - frontend
      - backend
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - gateway
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  maven_cache: 
