networks:
  frontend:
    name: frontend
  backend:
    name: backend
  database:
    name: database

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - "${SERVER_PORT}"
    networks:
      - backend
      - database

  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - app
    env_file:
      - .env
    expose:
      - "${GATEWAY_PORT}"
    networks:
      - backend
      - database

  web:
    container_name: web
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "${NGINX_PORT}"
    depends_on:
      - app
      - gateway
    networks:
      - frontend
      - backend

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - gateway
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  maven_cache: 
