services:
  postgres:
    image: postgres:latest
    container_name: historic_events
    environment:
      POSTGRES_USER: ${DB_ADMIN_LOGIN}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_DB: events
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"