services:
  postgres:
    image: postgres
    container_name: events
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events
    restart: unless-stopped
    ports:
      - "9999:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: