openapi: "3.1.0"
info:
  title: "WhatDayIsToday API"
  description: "WhatDayIsToday API"
  version: "1.0.0"
servers:
  - url: "https://WhatDayIsToday"
paths:
  /api/v1/events:
    post:
      summary: "POST api/v1/events"
      operationId: "createEvent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEventDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      summary: "PUT api/v1/events"
      operationId: "updateEvent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    get:
      summary: "GET api/v1/events"
      operationId: "getEventByDate"
      parameters:
        - name: "month"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int32"
        - name: "day"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /api/v1/events/{id}:
    get:
      summary: "GET api/v1/events/{id}"
      operationId: "getEventById"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    delete:
      summary: "DELETE api/v1/events/{id}"
      operationId: "deleteEvent"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    Year:
      type: "object"
      properties: { }
    MonthDay:
      type: "object"
      properties:
        month:
          type: "integer"
          format: "int32"
          nullable: true
    CreateEventDto:
      type: "object"
      properties:
        name:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        source:
          type: "string"
          nullable: true
        imageUrl:
          type: "string"
          nullable: true
        eventYear:
          nullable: true
          $ref: "#/components/schemas/Year"
        eventDate:
          nullable: true
          $ref: "#/components/schemas/MonthDay"
    EventDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          nullable: true
        name:
          type: "string"
          nullable: true
        description:
          type: "string"
          nullable: true
        source:
          type: "string"
          nullable: true
        imageUrl:
          type: "string"
          nullable: true
        eventYear:
          nullable: true
          $ref: "#/components/schemas/Year"
        eventDate:
          nullable: true
          $ref: "#/components/schemas/MonthDay"